dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4
  - 2.3
  - jruby-9.1.12.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
script:
  - bundle exec rake test
before_deploy:
  - bundle exec rake build
deploy:
  provider: rubygems
  api_key:
    secure: "Lq/S22rljsiZBNyfSTSF9wyNiP4s4yjeeHT37vor4CgijvP8CgIJcA6UtUN+EPLe/LlZEir/p8QHTPEwAtCg2ZoU2JmN+ul8IVboHlJ19NVKT92mhKDdGe6P3yKqbqFAEoteT9MXJ3xXysSWnWFLrEPAiOmNhuh+mnPOF8uPdgw="
  skip_cleanup: true
  on:
    rvm: 2.4
    tags: true
