dist: trusty
sudo: false
language: ruby

jobs:
  include:
    - env: &adoc-latest ASCIIDOCTOR_VERSION=2.0.7
      rvm: &ruby-latest 2.5
    - env: *adoc-latest
      rvm: 2.4
    - env: *adoc-latest
      rvm: jruby-9.1
    - env: *adoc-latest
      rvm: ruby-head
    - env: *adoc-latest
      rvm: jruby-head

    - env: ASCIIDOCTOR_VERSION=1.5.8
      rvm: *ruby-latest

    - env: ASCIIDOCTOR_VERSION=1.5.7.1
      rvm: *ruby-latest

    - env: ASCIIDOCTOR_VERSION=1.5.7
      rvm: *ruby-latest

    - env: ASCIIDOCTOR_VERSION=1.5.6.2
      rvm: 2.4

    - env: ASCIIDOCTOR_VERSION=1.5.6
      rvm: 2.4

    - env: ASCIIDOCTOR_VERSION="git:master"
      rvm: *ruby-latest

  allow_failures:
    - env: *adoc-latest
      rvm: ruby-head
    - env: *adoc-latest
      rvm: jruby-head
    - env: ASCIIDOCTOR_VERSION="git:master"
      rvm: *ruby-latest

script:
  - bundle exec rake test
  - bundle exec rake build:js

before_deploy:
  - gem install bundler
  - bundle exec rake build
  - bundle exec rake build:js

deploy:
  - provider: rubygems
    api_key:
      secure: "Lq/S22rljsiZBNyfSTSF9wyNiP4s4yjeeHT37vor4CgijvP8CgIJcA6UtUN+EPLe/LlZEir/p8QHTPEwAtCg2ZoU2JmN+ul8IVboHlJ19NVKT92mhKDdGe6P3yKqbqFAEoteT9MXJ3xXysSWnWFLrEPAiOmNhuh+mnPOF8uPdgw="
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_JOB_NUMBER#*.} = 1
  - provider: npm
    email: jakub@jirutka.cz
    api_key:
      secure: "ep+c5AmUy7wyl+mEuzVs+iV1a5wR5Kz7jzwC4KokF9zE7tDuPj7bCJorz+ZFC+IuzumBAKm4I8bSpnB6tqs/KEEoXnuSlMa94R3NlZ16xNuAVRRmXIxBzb6aF/ihF7p1yuXH2PWf8MqN82h/1XXiMHPYJnt2sToQnER60YyG0tM="  # 837f......d9f3
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_JOB_NUMBER#*.} = 1
