dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4
  - 2.3
  - jruby-9.1.12.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
script:
  - bundle exec rake test
